const app = {
  namespaced: true,
  state: {
    is_login: false,//true,//
    user_token: '',
    user: {
      "user_id": 0,
      "user_group_id": 0,
      "username": "DefaultTestUser",
      "email": "00000@test.com",
      "avatar": {
        "original": "/public/static/default/user/avatars/1/original/default.png",
        "small": "/public/static/default/user/avatars/1/small/default.png",
        "middle": "/public/static/default/user/avatars/1/middle/default.png",
        "large": "/public/static/default/user/avatars/1/large/default.png"
      },
      "cover": {
        "original": "/public/static/default/user/covers/1/original/default.png",
        "small": "/public/static/default/user/covers/1/small/default.png",
        "middle": "/public/static/default/user/covers/1/middle/default.png",
        "large": "/public/static/default/user/covers/1/large/default.png"
      },
      "password": null,
      "create_ip": "127.0.0.1",
      "create_location": "create_location",
      "last_login_time": 0,
      "last_login_ip": "114.514.114.514",
      "last_login_location": "last_login_location",
      "follower_count": 0,
      "followee_count": 0,
      "following_topic_count": 0,
      "following_article_count": 0,
      "following_question_count": 0,
      "article_count": 0,
      "question_count": 0,
      "answer_count": 0,
      "comment_count": 0,
      "reply_count": 0,
      "notification_unread": 0,
      // "inbox_system": 0,
      // "inbox_user_group": 0,
      // "inbox_private_message": 0,
      "headline": "headline",
      "bio": null,
      "blog": null,
      "company": null,
      "location": "location",
      "language": "zh_CN",
      "create_time": 0,
      "update_time": 0,
      "disable_time": 0,
      "user_group": {
        "user_group_id": 0,
        "user_group_name": "Message.AdminPage.UserGroups.User",
        "user_group_description": "Message.AdminPage.UserGroups.User",
        "user_group_icon": "mdi-account",
        "user_group_icon_show": false,
        "user_group_color": "primary",
        "user_group_user_count": 0,
        "create_time": 0,
        "update_time": 0,
        "delete_time": 0,
        "is_admin": false,
        "ability_normal_login": true,
        "ability_admin_login": false,
        "ability_admin_manage_user_group": false,
        "ability_admin_manage_user": false,
        "ability_admin_manage_topic": false,
        "ability_admin_manage_question": false,
        "ability_admin_manage_article": false,
        "ability_admin_manage_comment": false,
        "ability_admin_manage_answer": false,
        "ability_admin_manage_reply": false,
        "ability_admin_manage_report": false,
        "ability_admin_manage_option": false,
        "ability_create_article": false,
        "ability_create_question": false,
        "ability_create_answer": false,
        "ability_create_comment": false,
        "ability_create_reply": false,
        "ability_create_topic": false,
        "ability_edit_own_article": false,
        "ability_edit_own_question": false,
        "ability_edit_own_answer": false,
        "ability_edit_own_comment": false,
        "ability_edit_own_reply": false,
        "ability_edit_own_topic": false,
        "ability_delete_own_article": false,
        "ability_delete_own_question": false,
        "ability_delete_own_answer": false,
        "ability_delete_own_comment": false,
        "ability_delete_own_reply": false,
        "ability_delete_own_topic": false,
        "time_before_edit_article": 0,
        "time_before_edit_question": 0,
        "time_before_edit_answer": 0,
        "time_before_edit_comment": 0,
        "time_before_edit_reply": 0,
        "time_before_edit_topic": 0,
        "time_before_delete_article": 0,
        "time_before_delete_question": 0,
        "time_before_delete_answer": 0,
        "time_before_delete_comment": 0,
        "time_before_delete_reply": 0,
        "time_before_delete_topic": 0,
        "ability_edit_article_only_no_comment": false,
        "ability_edit_question_only_no_answer": false,
        "ability_edit_answer_only_no_comment": false,
        "ability_edit_question_only_no_comment": false,
        "ability_edit_comment_only_no_reply": false,
        "ability_edit_reply_only_no_reply": false,
        "ability_edit_topic_only_no_article_or_question": false,
        "ability_delete_article_only_no_comment": false,
        "ability_delete_question_only_no_answer": false,
        "ability_delete_answer_only_no_comment": false,
        "ability_delete_question_only_no_comment": false,
        "ability_delete_comment_only_no_reply": false,
        "ability_delete_reply_only_no_reply": false,
        "ability_delete_topic_only_no_article_or_question": false,
        "ability_edit_own_info": false,
        "ability_vote": false
      }
    },
    default_user: {
      "user_id": 0,
      "user_group_id": 0,
      "username": "DefaultTestUser",
      "email": "00000@test.com",
      "avatar": {
        "original": "/public/static/default/user/avatars/1/original/default.png",
        "small": "/public/static/default/user/avatars/1/small/default.png",
        "middle": "/public/static/default/user/avatars/1/middle/default.png",
        "large": "/public/static/default/user/avatars/1/large/default.png"
      },
      "cover": {
        "original": "/public/static/default/user/covers/1/original/default.png",
        "small": "/public/static/default/user/covers/1/small/default.png",
        "middle": "/public/static/default/user/covers/1/middle/default.png",
        "large": "/public/static/default/user/covers/1/large/default.png"
      },
      "password": null,
      "create_ip": "127.0.0.1",
      "create_location": "create_location",
      "last_login_time": 0,
      "last_login_ip": "114.514.114.514",
      "last_login_location": "last_login_location",
      "follower_count": 0,
      "followee_count": 0,
      "following_topic_count": 0,
      "following_article_count": 0,
      "following_question_count": 0,
      "article_count": 0,
      "question_count": 0,
      "answer_count": 0,
      "comment_count": 0,
      "reply_count": 0,
      "notification_unread": 0,
      // "inbox_system": 0,
      // "inbox_user_group": 0,
      // "inbox_private_message": 0,
      "headline": "headline",
      "bio": null,
      "blog": null,
      "company": null,
      "location": "location",
      "language": "zh_CN",
      "create_time": 0,
      "update_time": 0,
      "disable_time": 0,
      "user_group": {
        "user_group_id": 0,
        "user_group_name": "Message.AdminPage.UserGroups.User",
        "user_group_description": "Message.AdminPage.UserGroups.User",
        "user_group_icon": "mdi-account",
        "user_group_icon_show": false,
        "user_group_color": "primary",
        "user_group_user_count": 0,
        "create_time": 0,
        "update_time": 0,
        "delete_time": 0,
        "is_admin": false,
        "ability_normal_login": true,
        "ability_admin_login": false,
        "ability_admin_manage_user_group": false,
        "ability_admin_manage_user": false,
        "ability_admin_manage_topic": false,
        "ability_admin_manage_question": false,
        "ability_admin_manage_article": false,
        "ability_admin_manage_comment": false,
        "ability_admin_manage_answer": false,
        "ability_admin_manage_reply": false,
        "ability_admin_manage_report": false,
        "ability_admin_manage_option": false,
        "ability_create_article": false,
        "ability_create_question": false,
        "ability_create_answer": false,
        "ability_create_comment": false,
        "ability_create_reply": false,
        "ability_create_topic": false,
        "ability_edit_own_article": false,
        "ability_edit_own_question": false,
        "ability_edit_own_answer": false,
        "ability_edit_own_comment": false,
        "ability_edit_own_reply": false,
        "ability_edit_own_topic": false,
        "ability_delete_own_article": false,
        "ability_delete_own_question": false,
        "ability_delete_own_answer": false,
        "ability_delete_own_comment": false,
        "ability_delete_own_reply": false,
        "ability_delete_own_topic": false,
        "time_before_edit_article": 0,
        "time_before_edit_question": 0,
        "time_before_edit_answer": 0,
        "time_before_edit_comment": 0,
        "time_before_edit_reply": 0,
        "time_before_edit_topic": 0,
        "time_before_delete_article": 0,
        "time_before_delete_question": 0,
        "time_before_delete_answer": 0,
        "time_before_delete_comment": 0,
        "time_before_delete_reply": 0,
        "time_before_delete_topic": 0,
        "ability_edit_article_only_no_comment": false,
        "ability_edit_question_only_no_answer": false,
        "ability_edit_answer_only_no_comment": false,
        "ability_edit_question_only_no_comment": false,
        "ability_edit_comment_only_no_reply": false,
        "ability_edit_reply_only_no_reply": false,
        "ability_edit_topic_only_no_article_or_question": false,
        "ability_delete_article_only_no_comment": false,
        "ability_delete_question_only_no_answer": false,
        "ability_delete_answer_only_no_comment": false,
        "ability_delete_question_only_no_comment": false,
        "ability_delete_comment_only_no_reply": false,
        "ability_delete_reply_only_no_reply": false,
        "ability_delete_topic_only_no_article_or_question": false,
        "ability_edit_own_info": false,
        "ability_vote": false
      }
    },
  },
  getters: {
    GetIsLogin: state => state.is_login,
    GetUserToken: state => state.user_token,
    GetUser: state => state.user,
    GetDefaultUser: state => state.default_user,
  },
  mutations: {
    SetIsLogin(state, is_login) {
      state.is_login = is_login
    },
    SetUserToken(state, user_token) {
      state.user_token = user_token
    },
    SetUser(state, user) {
      state.user = user
    }
  },
  actions: {
    Set_IsLogin({ commit }, is_login) {
      commit('SetIsLogin', is_login)
    },
    Set_UserToken({ commit }, user_token) {
      commit('SetUserToken', user_token)
    },
    Set_User({ commit }, user) {
      commit('SetUser', user)
    },
  },
}
export default app
